### ISSUE TITLE
Allow color overriding

### ISSUE THREAD

**Issue by ialtamirano** [saeedalipoor/icono#15]
Allow for css color overriding.

http://jsfiddle.net/agLs7chu/

**Comment by saeedalipoor** [comment]
Oh, thanks alot about mentioning that. You should change color of icon directly for this version, in next version i will change something to support color inheritance. :)

**Comment by edtorba** [comment]
Following should work, also I can't find any reasons for setting default color on icons.

**file: icono.scss**
```
[class*="icono-"] {
  ...
  color: inherit;
  ...
}
```

**Comment by saeedalipoor** [comment]
Thanks @edtorba i just missed this issue and will fix this soon :)
