### ISSUE TITLE
Website in title is 404

### ISSUE THREAD

**Issue by Gerfaut** [saeedalipoor/icono#2]
Hi, 
Nice project, thank you ! 

The only problem I have is a mistake in the title : the website gives us a 404 (http://git.io/icono/). The website in the readme is perfectly working. 

Thank you for this great work !

**Comment by saeedalipoor** [comment]
thanks for reporting about that. that's ok now. :)

**Comment by Gerfaut** [comment]
Perfect ! :smile:
