### ISSUE TITLE
Keep classes lowercase and use dashes (not underscores or camelCase)

### ISSUE THREAD

**Issue by lipis** [saeedalipoor/icono#3]
http://codeguide.co/#css-classes

**Comment by saeedalipoor** [comment]
Thanks @lipis 
just do that for selecting class name with double click :)
If you thing that's annoying, i will change that.

**Comment by lipis** [comment]
In general I think it should be either one or the other.. (preferably the one with-the-dashes)


```
...
icono-locationArrow
icono-plusCircle
icono-checkCircle
icono-crossCircle
icono-exclamationCircle
...
```

should become

```
icono-location-arrow
icono-plus-circle
icono-check-circle
icono-cross-circle
icono-exclamation-circle
```

**Comment by edtorba** [comment]
+1, also would also be awesome if you will implement [BEM](https://bem.info/method/definitions/#Naming-for-independent-CSS-classes) naming convention. 
So instead of:

    icono-exclamation-circle

You would have:

    icono--exclamation-circle

**Comment by lipis** [comment]
I don't see any good reason for BEM... 

Just to name a few... here you are on how others doing it..
http://fortawesome.github.io/Font-Awesome/icons/
http://ionicons.com/
http://getbootstrap.com/components/#glyphicons

**Comment by edtorba** [comment]
Well... if they don't use it, it doesn't means that you shouldn't use it.

To name a few who uses BEM naming convention:
soundcloud.com
nhs.uk
csswizardry.com
fontello.com

**Comment by saeedalipoor** [comment]
I agree with @lipis for this case, because there are just icons here now and i think icono-blah or icono-blah-blah is better.
Thanks for your help :)
