### ISSUE TITLE
Responsive?

### ISSUE THREAD

**Issue by tunnckoCore** [saeedalipoor/icono#33]

**Comment by saeedalipoor** [comment]
No, If you mean something like http://www.responsiveicons.co.uk.

**Comment by tunnckoCore** [comment]
No. I believe it's possible if you add media queries.

**Comment by saeedalipoor** [comment]
What do you mean about responsive icon?

**Comment by tunnckoCore** [comment]
When resize browser windows they was not so good and remains almost the same size as when windows is maximized. But now it seems okey. So, nevermind.

**Comment by saeedalipoor** [comment]
I got your point. Should switch icon sizes from px to em.
#16
