### ISSUE TITLE
update your bower.json file

### ISSUE THREAD

**Issue by hemedani** [saeedalipoor/icono#37]
please update you'r main attr in `bower json` to 
```
  "main": "./build/icono.css",
```
because  of [wiredep](https://www.npmjs.com/package/wiredep)  read that instruction for more detail
the wiredep read `bower.json` file and inject dependency to the html, if you don't gave the right details to that, it can't does it's job properly.
thank's for you'r awesome font's

رفیق فایل باورت رو درست کن تا بشه با وایردپ درست انجکتش کنی توی اچ تی ام ال
التماس دعا

**Comment by saeedalipoor** [comment]
done 👍
https://github.com/saeedalipoor/icono/commit/c2bfd10eb701e03cc231a6b7eb385587b00dc22f
