### ISSUE TITLE
Could we get play, pause, fast forward and rewind icons?

### ISSUE THREAD

**Issue by Montoya** [saeedalipoor/icono#4]
And are you open to people contributing icons?

**Comment by joseluisq** [comment]
I'm interested in contributing too :+1:

**Comment by adamellsworth** [comment]
In my pull request there's some prototypes for play/pause, no ff/rw yet though

**Comment by saeedalipoor** [comment]
@Montoya , @joseluisq , @CodyReichert 
Sure, it's open to contribute :)
request icon like [this issue](https://github.com/saeedalipoor/icono/issues/7)
@adamellsworth thank you, I will check that.
