### ISSUE TITLE
about icono size

### ISSUE THREAD

**Issue by a13821190779** [saeedalipoor/icono#42]
how do you change the size?

**Comment by sgf** [comment]
[class*=icono-] {
  transform: scale(0.6,0.6);
}

**Comment by saeedalipoor** [comment]
You can rebuild icono with custom size. edit variables file and build it.
Also, you can wrap icon in a tag and scale that for now.
`<span class="x2"><i class="icono-home"></i></span>`
`<style>.x2{transform: scale(2)}</style>`
