### ISSUE TITLE
icono-frown mouth is misplaced

### ISSUE THREAD

**Issue by ksherlock** [saeedalipoor/icono#9]
![frown](https://cloud.githubusercontent.com/assets/964904/5704794/9d0da538-9a42-11e4-88f5-4f089d3bf2f5.png)

**Comment by saeedalipoor** [comment]
Hey @ksherlock , which browser did you screenshot?

**Comment by ksherlock** [comment]
Hello, that was from Safari Version 8.0.2 (10600.2.5) (OS X/Mavericks).  Firefox and chrome seem to display it fine.
